<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a69ee844-55cd-41dc-a2c3-a363f9bab309</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.26.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Microsoft.ML" Version="3.0.1" />
	<PackageReference Include="Microsoft.ML.ImageAnalytics" Version="3.0.1" />
	<PackageReference Include="SixLabors.ImageSharp" Version="2.1.9" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="mnist.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Generated\" />
  </ItemGroup>
	
</Project>
